argus:
  clusterName: yourname-eks-fargate-k8s
  lm:
    resource:
      globalDeleteAfterDuration: P0DT0H0M0S
  collector:
    replicas: 2
    size: small
    statefulsetSpec:
      template:
        spec:
          nodeSelector: {}
          priorityClassName: ""
          tolerations: []
collectorset-controller: {}
global:
  accessID: ACCESS ID
  accessKey: ACCESS KEY
  account: lmaccount
